"""empty message

Revision ID: a4d62647fac6
Revises:
Create Date: 2025-11-25 17:02:57.188406+00:00

"""

from typing import Sequence, Union

from alembic import op
import advanced_alchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a4d62647fac6"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spherical_horses",
        sa.Column("id", advanced_alchemy.types.guid.GUID(length=16), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("radius", sa.Float(), nullable=False),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            advanced_alchemy.types.datetime.DateTimeUTC(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_spherical_horses")),
    )
    op.create_index(
        op.f("ix_spherical_horses_name"), "spherical_horses", ["name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_spherical_horses_name"), table_name="spherical_horses")
    op.drop_table("spherical_horses")
    # ### end Alembic commands ###
